-- ============================================================================
-- Minuman @One - Warehouse Stock In (Barang Masuk / Produksi)
-- Date: 2026-08-15
-- Applies via: Supabase SQL Editor.
--
-- Contents:
--   1. WarehouseStockIn / WarehouseStockInItem tables + RLS
--   2. warehouse_stock_in_confirm RPC: posts WarehouseLedger (STOCK_IN) +
--      increments WarehouseStock, marks doc CONFIRMED.
-- ============================================================================

-- Ensure the warehouse movement type exists (base schema may or may not have it).
alter type public."WarehouseMovementType" add value if not exists 'STOCK_IN';

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public."WarehouseStockIn" (
  id            bigint generated by default as identity primary key,
  doc_number    text not null,
  doc_date      date not null default current_date,
  warehouse_id  bigint references public."Warehouse"(id),
  status        text not null default 'DRAFT',
  total_qty     integer not null default 0,
  notes         text,
  created_by    bigint references public."User"(id),
  confirmed_by  bigint references public."User"(id),
  confirmed_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public."WarehouseStockInItem" (
  id           bigint generated by default as identity primary key,
  stock_in_id  bigint not null references public."WarehouseStockIn"(id) on delete cascade,
  product_id   bigint not null references public."Product"(id),
  qty          integer not null default 0,
  unit_id      bigint references public."Unit"(id),
  remark       text
);

create index if not exists idx_stock_in_item_header on public."WarehouseStockInItem"(stock_in_id);
create index if not exists idx_stock_in_warehouse on public."WarehouseStockIn"(warehouse_id);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

alter table public."WarehouseStockIn" enable row level security;
alter table public."WarehouseStockInItem" enable row level security;

drop policy if exists p_WarehouseStockIn_select on public."WarehouseStockIn";
create policy p_WarehouseStockIn_select on public."WarehouseStockIn"
  for select to authenticated
  using (public.current_user_role() = 'OWNER' or created_by = public.current_user_id());

drop policy if exists p_WarehouseStockIn_insert on public."WarehouseStockIn";
create policy p_WarehouseStockIn_insert on public."WarehouseStockIn"
  for insert to authenticated
  with check (public.current_user_role() = 'OWNER');

drop policy if exists p_WarehouseStockIn_update on public."WarehouseStockIn";
create policy p_WarehouseStockIn_update on public."WarehouseStockIn"
  for update to authenticated
  using (public.current_user_role() = 'OWNER')
  with check (public.current_user_role() = 'OWNER');

drop policy if exists p_WarehouseStockIn_delete on public."WarehouseStockIn";
create policy p_WarehouseStockIn_delete on public."WarehouseStockIn"
  for delete to authenticated
  using (public.current_user_role() = 'OWNER');

drop policy if exists p_WarehouseStockInItem_select on public."WarehouseStockInItem";
create policy p_WarehouseStockInItem_select on public."WarehouseStockInItem"
  for select to authenticated
  using (exists (
    select 1 from public."WarehouseStockIn" h
    where h.id = stock_in_id
      and (public.current_user_role() = 'OWNER' or h.created_by = public.current_user_id())
  ));

drop policy if exists p_WarehouseStockInItem_insert on public."WarehouseStockInItem";
create policy p_WarehouseStockInItem_insert on public."WarehouseStockInItem"
  for insert to authenticated
  with check (public.current_user_role() = 'OWNER');

drop policy if exists p_WarehouseStockInItem_update on public."WarehouseStockInItem";
create policy p_WarehouseStockInItem_update on public."WarehouseStockInItem"
  for update to authenticated
  using (public.current_user_role() = 'OWNER')
  with check (public.current_user_role() = 'OWNER');

drop policy if exists p_WarehouseStockInItem_delete on public."WarehouseStockInItem";
create policy p_WarehouseStockInItem_delete on public."WarehouseStockInItem"
  for delete to authenticated
  using (public.current_user_role() = 'OWNER');

-- ---------------------------------------------------------------------------
-- RPC: warehouse_stock_in_confirm
-- ---------------------------------------------------------------------------

drop function if exists public.warehouse_stock_in_confirm(integer);

create or replace function public.warehouse_stock_in_confirm(p_stock_in_id integer)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_doc     record;
  v_item    record;
  v_user_id int := public.current_user_id();
  v_wh_stock int;
  v_balance int;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select * into v_doc
  from public."WarehouseStockIn"
  where id = p_stock_in_id
  for update;

  if not found then
    raise exception 'Barang masuk % tidak ditemukan', p_stock_in_id;
  end if;

  if v_doc.status <> 'DRAFT' then
    raise exception 'Barang masuk % sudah berstatus %', p_stock_in_id, v_doc.status;
  end if;

  if v_doc.warehouse_id is null then
    raise exception 'Gudang tujuan wajib diisi';
  end if;

  for v_item in
    select i.product_id, i.qty, i.remark
    from public."WarehouseStockInItem" i
    where i.stock_in_id = p_stock_in_id
    order by i.id
  loop
    if v_item.qty is null or v_item.qty <= 0 then
      continue;
    end if;

    select ws.qty_available into v_wh_stock
    from public."WarehouseStock" ws
    where ws.warehouse_id = v_doc.warehouse_id
      and ws.product_id = v_item.product_id
    for update;

    v_balance := coalesce(v_wh_stock, 0) + v_item.qty;

    if not found then
      insert into public."WarehouseStock"
        (warehouse_id, product_id, batch_id, qty_available, version, updated_at, condition)
      values
        (v_doc.warehouse_id, v_item.product_id, null, v_item.qty, 1, now(), 'GOOD');
    else
      update public."WarehouseStock"
         set qty_available = v_balance,
             version = version + 1,
             updated_at = now()
       where warehouse_id = v_doc.warehouse_id
         and product_id = v_item.product_id;
    end if;

    insert into public."WarehouseLedger"
      (warehouse_id, sales_id, product_id, movement_type, qty, balance,
       reference_type, reference_id, notes, created_by, transaction_date)
    values
      (v_doc.warehouse_id, null, v_item.product_id,
       'STOCK_IN'::public."WarehouseMovementType", v_item.qty, v_balance,
       'WarehouseStockIn', v_doc.doc_number, v_item.remark, v_user_id, v_doc.doc_date);
  end loop;

  update public."WarehouseStockIn"
     set status = 'CONFIRMED',
         confirmed_by = v_user_id,
         confirmed_at = now(),
         updated_at = now()
   where id = p_stock_in_id;

  return jsonb_build_object('success', true, 'stock_in_id', p_stock_in_id, 'status', 'CONFIRMED');
exception
  when others then
    raise exception 'warehouse_stock_in_confirm failed: %', SQLERRM;
end;
$$;

revoke execute on function public.warehouse_stock_in_confirm(integer) from public, anon;
grant execute on function public.warehouse_stock_in_confirm(integer) to authenticated;
